MODEL: gpt-3.5-turbo  # -0613
TEMPERATURE: 0.
MAX_TOKENS: 8
SLEEP_PER_INFER: 0

PROMPT_HEAD: "Please answer the question according to the context and candidate answers. Each candidate answer is associated with a confidence score within a bracket. The true answer must be included in the candidate answers.\n\n"
LINE_PREFIX: "===\n"
N_EXAMPLES: 20
K_CANDIDATES: 10
T_INFER: 1
noContext: False
noCaption: False
confidence_threshold: 0.7
Context_cut: realtime  # static, ct_cut, realtime
useCaption: MinGPT4 # None #  #  # 